services:
  # moviedb.nl
  production:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./data:/app/data
    environment:
      - SERVICE_NAME=streamlit_production
      - PGHOST=postgres
      - PGDATABASE=moviedb_production
      - POSTGRES_DB=moviedb_production
    env_file:
      - .env
    restart: no

  # dev.moviedb.nl
  develop:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8502:8501"
    volumes:
      - ./data:/app/data
    environment:
      - SERVICE_NAME=streamlit_develop
      - PGHOST=postgres
      - PGDATABASE=moviedb_develop
      - POSTGRES_DB=moviedb_develop
    env_file:
      - .env
    restart: no

  # localhost:8501
  local:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "127.0.0.1:8501:8501"
    volumes:
      - ./src:/app/src
      - ./data:/app/data
    environment:
      - SERVICE_NAME=streamlit_local
      - PGHOST=postgres
    env_file:
      - .env
      - .env.branch
    restart: no

  postgres:
    image: pgvector/pgvector:pg18-trixie
    restart: always
    ports:
      - "127.0.0.1:${PGPORT}:${PGPORT}"
    volumes:
      - postgres:/var/lib/postgresql
    env_file:
      - .env
    environment:
      - SERVICE_NAME=postgres
    shm_size: 1g

volumes:
  postgres:


